bbs/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import ShousaiView
 
 
app_name = "bbs"
 
urlpatterns = [
   
    path('BulletinBoard/', views.BulletinBoardView.as_view(), name='BulletinBoard'),
 
    path('Posts', views.PostsView.as_view(), name='Posts'),
    path('PostsComplate/<str:name>/', views.PostsComplateView.as_view(), name='PostsComplate'),
 
    path('Posts/<int:material>/<int:materialamount>/', views.save_material, name='savematerial'),
    path('Posts/<str:materialname>/', views.get_materials, name='getmaterial'),
   
    path('MyBulletinBoard/', views.MyBulletinBoardView.as_view(), name='MyBulletinBoard'),
    path('edit/<int:post_id>/', views.EditView.as_view(), name='edit'),
    path('editcomplate/', views.Editcomplate.as_view(), name='editcomplate'),
    path('bbs/delete/<int:post_id>/', views.DeleteView.as_view(), name='PostsDelete'),
    path('bbs/delete/', views.DeleteComplateView.as_view(), name='PostsDeleteComplate'),
 
    path('toggle_favorite/<int:post_id>/', views.toggle_favorite, name='toggle_favorite'),
   
    path('favorite/', views.FavoriteView.as_view(), name='favorite'),
    path('ranking/', views.RankView.as_view(), name='ranking'),
    
    path('shousai/<int:post_id>/', ShousaiView.as_view(), name='shousai'),
]

cookapp/urls.py
from django.urls import path
from . import views
from .views import  KazokuHenkoView
from django.contrib.auth import views as auth_views
from .views import DietaryHistoryDetailView


app_name = "cookapp"

urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('Login1/', views.CustomLogin1View.as_view(), name='Login1'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('setting/', views.SettingView.as_view(), name='setting'),
    path('acount_setting/', views.AcountSettingView.as_view(), name='acount_setting'),
    path('family_info/', views.FamilyInfoView.as_view(), name='family_info'),
    path('body_info_update/', views.BodyInfoUpdateView.as_view(), name='body_info_update'),
    path('body_info_ok/', views.BodyInfoOkView.as_view(), name='body_info_ok'),
    path('notification_setting/', views.NotificationSettingView.as_view(), name='notification_setting'),
    path('subscription_setting/', views.SubscriptionSettingView.as_view(), name='subscription_setting'),
    path('subscription_login/', views.SubscriptionLoginView.as_view(), name='subscription_login'),
    path('subscription_login_ok/', views.SubscriptionLoginOkView.as_view(), name='subscription_login_ok'),
    path('subscription_kaiyaku/', views.SubscriptionKaiyakuView.as_view(), name='subscription_kaiyaku'),
    path('subscription_kaiyaku_ok/', views.SubscriptionKaiyakuOkView.as_view(), name='subscription_kaiyaku_ok'),
    path('osirase/', views.OsiraseView.as_view(), name='osirase'),
    path('questions/', views.QuestionsView.as_view(), name='questions'),
    path('username/', views.UsernameView.as_view(), name='username'),
    path('username_henko_ok/', views.UsernameOkView.as_view(), name='username_henko_ok'),
    path('email/', views.EmailView.as_view(), name='email'),
    path('email_henko_ok/', views.EmailOkView.as_view(), name='email_henko_ok'),
    path('password/', views.PasswordView.as_view(), name='password'),
    path('password_henko_ok/', views.PasswordOkView.as_view(), name='password_henko_ok'),
    path('kazoku_add/', views.KazokuaddView.as_view(), name='kazoku_add'),
    path('kazoku_add_ok/', views.KazokuaddOkView.as_view(), name='kazoku_add_ok'),
    path('shokujirireki/', views.DietaryHistoryView.as_view(), name='dietaryhistory'),
    path('kazoku/henko/<int:family_id>/', KazokuHenkoView.as_view(), name='kazoku_henko'),
    path('kazoku_henko_ok/<int:family_id>/', views.KazokuHenkoOkView.as_view(), name='kazoku_henko_ok'),
    path('kazoku/kakunin/<int:family_id>/', views.KazokuKakuninView.as_view(), name='kazoku_kakunin'),
    path('health_graph/', views.HealthGraphView.as_view(), name='health_graph'),
    path('confirm_taikai/', views.confirm_taikai, name='confirm_taikai'),
    path('taikai_ok/', views.taikai_ok, name='taikai_ok'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('kazoku/sakujo/<int:family_id>/', views.KazokuSakujoView.as_view(), name='kazoku_sakujo'),
    path('kazoku_sakujo_ok/<int:family_id>/', views.KazokuSakujoOkView.as_view(), name='kazoku_sakujo_ok'),
    path('kiyaku/', views.KiyakuView.as_view(), name='kiyaku_kiyaku'),
    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='/password_reset/done/'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),
    path('dietaryhistorydetail/<str:date>/<str:cookname>/', DietaryHistoryDetailView.as_view(), name='dietaryhistorydetail'),
    
]

cookingnavi/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path("cook/", include('cookapp.urls')),
    path("", include('account.urls')),
    path("administrator/", include('administrator.urls')),
    path("bbs/",include('bbs.urls')),
    path("healthmanagement/", include('healthmanagement.urls')),
    path("buylist/", include('kaimonorisuto.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cookapp/views.py
import json
from django.shortcuts import get_object_or_404, render, redirect

from administrator.models import Cookimage, Recipe
from healthmanagement.models import Menu, Menucook
from .forms import EmailForm, UsernameForm, PasswordForm, BodyInfoUpdateForm, FamilyForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.contrib import messages
from .models import Familymember, Familyallergy, News, Question, Weight
from account.models import  Userallergy 
from django.http import JsonResponse
import logging
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, get_user_model, authenticate, login
from django.urls import reverse
import calendar
import json
from django.shortcuts import render
from django.views import View
from django.contrib.auth.views import PasswordResetDoneView
from datetime import datetime
from urllib.parse import unquote

 
 
logger = logging.getLogger(__name__)
 
class IndexView(TemplateView):
    template_name='index.html'
 
class CustomLogin1View(TemplateView):
    template_name='Login1.html'
 
class HomeView(TemplateView):
    template_name='home/home.html'
    def get(self, request, *args, **kwargs):
        logging.debug(f"Session info: {self.request.session.items()}")  # セッション内容をログに出力
        logging.debug(f"User is authenticated: {request.user.is_authenticated}")
        return super().get(request, *args, **kwargs)
    # def get_context_data(self, **kwargs):
    #     logging.debug(f"User ID: {self.request.user.id}")
    #     user = self.request.user  # または request.user
 
    #     # ユーザーIDでデータベースから再取得することも可能
    #     id = self.request.session.get('_auth_user_id')
    #     user = User.objects.get(user_id=id)
    #     context = super().get_context_data(**kwargs)
    #     context['user'] = user  # ログインしているユーザー情報を渡す
    #     return context
 

class SettingView(TemplateView):
    template_name='setting/setting.html'
   
 
class AcountSettingView(LoginRequiredMixin, TemplateView):
    template_name = 'acount/acount_setting.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            logger.error("Error 401: Unauthorized access attempt to AccountSettingView.")
            logging.debug(f"Session info: {request.session.items()}")  # セッション内容をログに出力
            # ログインしていない場合はリダイレクト
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
 
 
class NotificationSettingView(TemplateView):
    template_name='notification/notification.html'
 
 
class SubscriptionSettingView(TemplateView):
    template_name='sabusuku/setting/sabusuku_setting.html'
 
class SubscriptionLoginView(TemplateView):
    template_name='sabusuku/touroku/sabusuku_login.html'
 
class SubscriptionLoginOkView(LoginRequiredMixin, TemplateView):
    template_name='sabusuku/touroku/sabusuku_login_ok.html'
 
    def post(self, request, *args, **kwargs):
        user = request.user
        # サブスク登録処理
        if user.subscribeflag:
            # subscribeflag が True の場合（入会済み）
            messages.warning(request, 'すでに入会済みです。')
            return redirect('cookapp:subscription_login')
        else:
            # subscribeflag が False の場合（未入会）
            user.subscribeflag = True  # サブスクフラグをTrueに設定
            user.subjoin = timezone.now().date()  # 入会日を現在の日付に設定
            user.save()
 
            # サブスク登録完了ページに遷移
            return render(request, self.template_name)
 
   
class SubscriptionKaiyakuView(TemplateView):
    template_name='sabusuku/kaiyaku/sabusuku_kaiyaku.html'
 
class SubscriptionKaiyakuOkView(LoginRequiredMixin, TemplateView):
    template_name='sabusuku/kaiyaku/sabusuku_kaiyaku_ok.html'
 
    def post(self, request, *args, **kwargs):
        user = request.user
        # サブスク退会処理
        if user.subscribeflag:
            # subscribeflag が True の場合（入会済み）
            user.subscribeflag = False  # サブスクフラグをFalseに戻す
            user.unsub = timezone.now().date()  # 退会日を現在の日付に設定
            user.save()
 
            # サブスク解約完了ページに遷移
            return render(request, self.template_name)
        else:
            # subscribeflag が False の場合（未入会）
            messages.warning(request, '未入会です。')
            return redirect('cookapp:subscription_kaiyaku')
 
 
class OsiraseView(TemplateView):
    template_name='osirase/osirase.html'
    def get(self, request, *args, **kwargs):
        user = request.user
        news = News.objects.all().values('news_id','title','update_time', 'content').order_by('update_time')
        newslist = list(news)
        logging.debug(newslist)
        context = {
            'news': news,
        }
        return render(request, self.template_name, context)
        
 
class QuestionsView(TemplateView):
    template_name='questions/questions.html'
    def get(self, request, *args, **kwargs):
        question = Question.objects.all().values('question_id','question','answer').order_by('question_id')
        questionlist = list(question)
        logging.debug(questionlist)
        context = {
            'question': questionlist,
        }
        return render(request, self.template_name, context)
 
 
class UsernameView(LoginRequiredMixin, TemplateView):
    template_name = 'acount/name/username_henko.html'
    def get(self, request, *args, **kwargs):
        form = UsernameForm()
        return render(request, self.template_name, {'form': form})
   
    def post(self, request, *args, **kwargs):
        form = UsernameForm(request.POST)
        if form.is_valid():
            new_username = form.cleaned_data['new_username']
           
            # メールアドレスの更新
            user = request.user
            user.name = new_username
            user.save()

            return redirect('cookapp:username_henko_ok')  # プロフィールページなどにリダイレクト
       
        return render(request, self.template_name, {'form': form})
 
class UsernameOkView(TemplateView):
    template_name = "acount/name/username_henko_ok.html"
 
 
class EmailView(LoginRequiredMixin, TemplateView):
    template_name = 'acount/email/email_henko.html'
    def get(self, request, *args, **kwargs):
        form = EmailForm()
        return render(request, self.template_name, {'form': form})
   
    def post(self, request, *args, **kwargs):
        form = EmailForm(request.POST)
        if form.is_valid():
            new_email = form.cleaned_data['new_email']
           
            # メールアドレスの更新
            user = request.user
            user.email = new_email
            user.save()

            return redirect('cookapp:email_henko_ok')  # プロフィールページなどにリダイレクト
       
        return render(request, self.template_name, {'form': form})
 
class EmailOkView(TemplateView):
    template_name = 'acount/email/email_henko_ok.html'
 
 
class PasswordView(LoginRequiredMixin, TemplateView):
    template_name = 'acount/password/password_henko.html'
    def get(self, request, *args, **kwargs):
        form = PasswordForm()
        return render(request, self.template_name, {'form': form})
   
    def post(self, request, *args, **kwargs):
        form = PasswordForm(request.POST)
        if form.is_valid():
            current_password = form.cleaned_data['current_password']
            new_password = form.cleaned_data['new_password']
 
            if not request.user.check_password(current_password):
                messages.error(request, "ログイン中のユーザーと異なるパスワードを入力しました。")
            else:
                # パスワードの更新
                user = request.user
                user.set_password(new_password)
                user.save()

                user = authenticate(email=user.email, password=new_password)
                if user is not None:
                    login(request, user)

                return redirect('cookapp:password_henko_ok')  # プロフィールページなどにリダイレクト
       
        return render(request, self.template_name, {'form': form})
 
class PasswordOkView(TemplateView):
    template_name = 'acount/password/password_henko_ok.html'
 
 
class BodyInfoUpdateView(LoginRequiredMixin, TemplateView):
    template_name = 'sintai/sintai_henko.html'

    def get(self, request, *args, **kwargs):
        initial_data = {
            'name': request.user.name,
            'birthdate': request.user.age,
            'gender': request.user.gender,
            'height': request.user.height,
            'weight': request.user.weight,
            'allergies': [ua.allergy for ua in Userallergy.objects.filter(user=request.user)]
        }
        form = BodyInfoUpdateForm(initial=initial_data)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        family_member = Familymember.objects.filter(user=request.user).first()
        form = BodyInfoUpdateForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            birthdate = form.cleaned_data['birthdate']
            gender = form.cleaned_data['gender']
            allergies = form.cleaned_data['allergies']
            height = form.cleaned_data['height']
            weight = form.cleaned_data['weight']
            logging.debug(birthdate)
            modified_birthdate = birthdate.strftime("%Y-%m-%d")  # フォーマットを修正

            if name != request.user.name:
                messages.error(request, "ログイン中のユーザーと異なるユーザー名を入力しました。")
            else:
                user = request.user
                user.age = modified_birthdate
                user.gender = gender

cookapp/templates/keijiban/BulletinBoard.html
{% extends 'baseuser.html' %}
{% load static %}
 
{% block title %}主菜選択{% endblock %}
 
{% block content %}
 
<head>
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/keijiban/bulletinboard.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
 
<div class="search-bar-container">
    <form action="{% url 'bbs:BulletinBoard' %}" method="get">
        <input type="text" name="search_query" placeholder="投稿を検索する..." class="search-bar" value="{{ search_query }}">
        <button type="submit" class="search-btn">検索</button>
    </form>
    <a href="{% url 'bbs:Posts' %}">
        <button class="post-btn">レシピを投稿する</button>
    </a>
</div>
 
<div class="content-container">
    <aside class="sidebar">
        <a href="{% url 'bbs:MyBulletinBoard' %}"><button type="button">自分が投稿したもの</button></a>
        <a href="{% url 'bbs:favorite' %}"><button type="button">お気に入り</button></a>
        <a href="{% url 'bbs:ranking' %}"><button type="button">いいね数順</button></a>
        <a href="{% url 'cookapp:home' %}"><button type="button">ホーム</button></a>
    </aside>
 
    <main class="main-content">
        {% if bbs_with_images %}
            {% for bbs_entry in bbs_with_images %}
                <div class="post-card">
                    <div class="post-details">
                        <h3>{{ bbs_entry.post.name }}</h3>
                        <a href="{% url 'bbs:shousai' bbs_entry.post.post_id %}">
                            <img src="{{ bbs_entry.images }}" alt="Post image" class="img-fluid mb-3">
                        </a>
                        <div class="button-container">
                            <!-- お気に入りボタン -->
                            <button class="like-btn" onclick="toggleLike(this, '{{ bbs_entry.post.post_id }}')">
                                {% if bbs_entry.is_favorite %}
                                    <i class="fas fa-heart"></i>  <!-- お気に入り状態（赤色） -->
                                {% else %}
                                    <i class="far fa-heart"></i>  <!-- 初期状態（灰色） -->
                                {% endif %}
                            </button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>検索結果が見つかりませんでした。</p>
        {% endif %}
    </main>
</div>
 
{% endblock %}
 
{% block scripts %}
<script>
    // CSRFトークンを取得するヘルパー関数
    function getCookie(name) {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
            const [key, value] = cookie.trim().split('=');
            if (key === name) {
                return decodeURIComponent(value)
            }
        }
        return null;
    }
 
    function toggleLike(button, post_id) {
        // CSRFトークンを取得
        const csrfToken = getCookie('csrftoken');
 
        // URLを設定
        const url = '{% url "bbs:toggle_favorite" 0 %}'.replace('0', post_id);
 
        fetch(url, {
            method: 'POST',
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'Content-Type': 'application/json',
                'X-CSRFToken': csrfToken, // CSRFトークンをヘッダに追加
            },
            body: JSON.stringify({
                post_id: post_id  // リクエストボディにpost_idを含める
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'added') {
                button.classList.add('liked');
                button.querySelector('i').classList.replace('far', 'fas');
            } else {
                button.classList.remove('liked');
                button.querySelector('i').classList.replace('fas', 'far');
            }
        })
        .catch(error => console.error('Error:', error));
    }
</script>
{% endblock %}